#
# CONFIGURATION
#

# SITE
language: "en-us"
encoding: "utf-8"
title: "Evolution"
title_after: ""
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
author: "Bov Academy"

# ROUTES
baseurl: ""
url: "http://localhost:4000"
root: /
permalink: /:categories/:title/

# BUILD SETTINGS
# gems:
#   - jekyll-feed
markdown: kramdown
sass:
    sass_dir: /assets/styles/_sass
    style: compressed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

# COLLECTIONS
collections:
  components:
    output: false
